branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: documentation
    prefix: docs/
  - label: '*'
    prefix: issues/
branchName: 'issue-${issue.number%4}-${issue.title,}'
autoCloseIssue: true
