branches:
  - label: 'initial push'
    prefix: initial/
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: documentation
    prefix: docs/
  - label: '*'
    prefix: issue/
gitSafeReplacementChar: '-'
branchName: '${issue.number%4}-${issue.title[0,64],}'

